remote_theme: dieghernan/chulapa

# Find errors on this file with http://www.yamllint.com/

# Chulapa docs: https://dieghernan.github.io/chulapa/docs/02-config

# A. Site Settings /SEO options
# Overall options for your site, would affect your site SEO
# Default values are explained
locale                  :     #default["en-US"] format language-TERRITORY , e.g fr, en-GB, es-MX, pt-BR
title                   : Human Sociality Lab    #default["repository_name"]
#title_separator         :     #default [" | "]
#subtitle                : #Chulapa Jekyll Theme starter pack    #default [your-repository-tagline]  
description             : Research on human social life for the 21st century #default [your-repository-tagline]
url                     :     https://www.socialitylab.org #See baseurl - On Github Pages you may leave it blank - If you use CNAME use your domain
baseurl                 :     #On Github Pages you may leave it blank. Have a look to: https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/
words_per_minute        :     #default[200]
timezone                :     America/Los_Angeles #"Europe/Madrid ,see https://jekyllrb.com/docs/configuration/options/ and https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# SEO
og_image                :     /images/logo_2023.png #default[author.avatar (see below)] or [github-avatar]
twitter_site            :     SocialityLab #Avoid @
author:
  name                  :  Human Sociality Lab   # Name Surname Company
  avatar                :   /images/logo_2023.png  # Try a square file. Info: Your github avatar on https://github.com/[USERNAME].png
  location              :  "Pullman, USA"   # New York, USA 
#  links:                
#    - url:  #A link or email: https://twitter.com/jack, mail@example.com
#      icon: # A Fontawesome 5 code: fab fa-twitter - see https://fontawesome.com/
#    - url:  # Another link
#      icon: # Anothet FontAwesome code

fa_version: #default ["6"] Use 6 or 5
fa_kit_code: # Your FontAwesome kit code. If not provided a free hosted version (slower) will be loaded:  https://fontawesome.com/ 
fa_v4_support: #Bool Add FontAwesome 4 support 
# Web tracking - Google services https://analytics.google.com/analytics/web/
# gtag_id is the preferred option, see https://developers.google.com/analytics/devguides/collection/gtagjs/migration?hl=en
# analytics provided for backwards compatibility
gtag_id                 :  
analytics_id            :  

# Search providers
# Available free search engines:
# - lunr https://lunrjs.com/ 
# - algolia v4 https://www.algolia.com/ - needs further configuration
# - google custom search engine https://cse.google.es/ 
search:
  provider              : lunr #Select a provider for enable search: lunr, algolia, google
  label                 :  Search our site #default ["Search"] Text on navbar when search is enabled 
  landing_page          :  #default ["/search"] Link on navbar 
  lunr_maxwords         :  #default [30] lunr only - May slow down your site build
  algolia_logo          :  true #Displays algolia logo. Should be set to true if you are on a community plan, otherwise false.  

google_cse_id: #Your cse id
# This site uses jekyll-algolia plugin https://community.algolia.com/jekyll-algolia/
# Recommended additional configuration provided, could be modified. Add your own parameters
algolia:                                                                   
  application_id        : 
  index_name            : 
  search_only_api_key   : 
  files_to_exclude:         #Optional
    - _layouts/*.html
    - _includes/*.html
  extensions_to_index:      #Optional
    - html
    - md
  searchableAttributes:     #Optional                                                    
    - title                                                                    
    - headings                                                                 
    - unordered(content)                                                       
    - unordered(subtitle)                                                      
    - unordered(categories)                                                    
    - unordered(collection)                                                    
    - unordered(tags) 
  customRanking:            #Optional
    - desc(include_on_search)
    - desc(title)
    - desc(content) 
    - desc(subtitle)
    
comments:
  provider:         #Enable comments via Disqus, giscus or Cactus.chat
  disqus_shortname: #Your site id : check your address https://{{ disqus.shortname }}.disqus.com/admin/
  cactus_shortname: #Your site id as registered with Cactus.chat
  
# B. Navigation
# Configure your navbar and the footer of your site

# Navbar: 
#   "brand" options would be set on the left side of your navbar
#   "nav" would be set on the right side. Two-level nav links available
navbar:
  style     :  dual #default is the classical top navbar, set "fab" for a floating action button navbar or "dual"
  font      :  18px/1.4
  expand    :  # At which device size expand the navbar menu. default[md] https://getbootstrap.com/docs/4.5/layout/overview/
  brand:
    title   :  The HSL # Title in navbar
    url     :  # default["url/baseurl"]
    img     :  /images/logo_2023_thumbnail.png # An small image, try 30x30px
  nav:
  - title   : Research # Label
    url     : /projects/ # url	
  - title   : Team
    child:
    - title: Team members
      url: /team
    - title: Alumni
      url: /alumni
    - title: Join us!
      url: /join
  - title: Publications and CV
    child:
    - title: Publications
      url: /pubs
    - title: CV
      url: /cv
  - title: SciComm
    url: /media
  - title: Funders
    url: /funders
  - title: Commitments
    url: /commitments

#Social links to be placed on your site footer
footer:
  links:
    - label : HSL on Twitter # Label
      icon  : fab fa-twitter-square # Fontawesome 5 icon
      url   : https://www.twitter.com/SocialityLab # A link or email: https://twitter.com/jack, mail@example.com
    - label: Land Acknowledgment
      icon: fas fa-map-marked-alt
      url: https://wsu.edu/about/land-acknowledgement/
  copyright: # default is © <year> <name> 

# C. Theme Settings
# Google Fonts https://fonts.google.com/, add as many as you need
googlefonts:
 # - url : # 'https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap'

# Theme and colors
chulapa-skin: 
  highlight     :  # default["default"]
  skin         :  gitdev-dark # Optional predefined skins
  autothemer    :  true # Bool: Use autotheming
  vars  :
    primary: "#FF304F"
    secondary: "#CACACA"
    success: "#015668"
    danger: "#06648C"
    info: "#0F81C7"
    warning: "#0DE2EA"
    light: "#ececec"
    dark: "#222222"
    
# Doesn't work because of the theme adopted above but would be nice!
    
# D. Jekyll Defaults and collections: see https://jekyllrb.com/

# Blog pagination: on this site /blog/index.html. https://jekyllrb.com/docs/pagination/ AND here https://github.com/scandio/jekyll-paginate-multiple
# Couldn't make multiple work without GitBash or similar
#paginate_multiple:
#  - paginate: 10
#    paginate_path: '/pubs/page:num/'
#    sub_dir: '/pubs'
#  - paginate: 10
#    paginate_path: '/media/page:num/'
#    sub_dir: '/media'

paginate: 10
paginate_path: "/pubs/page:num/"
paginator_maxnum: 10  #default[3] Custom: max of number to be displayed on the paginator

# Collections https://jekyllrb.com/docs/step-by-step/09-collections/
collections:
  funders:
    output: true
    permalink: /funders/:path
  media:
    output: true
    permalink: /media/:path

#collections_dir     : 
#permalink           : /:year:month:day_:title/


# Defaults https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      header_type: "base"
      #header_img: /images/wordcloud_230708.png
      include_on_search   : false
      cloudtag_url        : /tags #This is where the link on tags would redirect
      cloudcategory_url   : /categories #This is where the link on categories would redirect
  -
    scope:
      path: ""
      type: "posts"
    values:
      header_type       : "post"
      include_on_search : true
      include_on_feed   : true
      show_date         : true
      show_related      : true
      show_bottomnavs   : true
      show_sociallinks  : true
      show_comments     : true
      show_tags         : true
      show_categories   : true
      show_author       : true
      show_breadcrumb   : true
      breadcrumb_list   :
        - label: Publications
          url: /pubs/
  -
    scope:
      path: ""
      type: "cheatsheet"
    values:
      header_type       : "hero"
      show_bottomnavs   : true
      show_sociallinks  : true
      include_on_search : true
      show_breadcrumb   : true
      breadcrumb_list   :
        - label: Cheatsheets
          url: /cheatsheets


# XX. Other settings - no need to modify
# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  blanklines: true

plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-sitemap


# Exclude these files from production site
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor

include:
 - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  footnote_backlink: '&uarr;'
  entity_output: as_char
  toc_levels: 2..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  toc_levels: 1..6

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

